<?xml version="1.0"?>
<robot name="arlobot_global" xmlns:xacro="http://ros.org/wiki/xacro">

    <!-- This file contains global parameters (primarily constants) that are used by various xacro files and that are
         static for the Arlobot robot
    -->

    <xacro:property name="PI" value="3.1415" />


    <!-- Convenience properties for angles, cosine and sine calculations
         Note: ROS Jade allows actual cos/sin function calls to perform these calculations, but alas, we are not on
         Jade :-(.  But, doing this can make it a simple transition.  Just update these properties and everything will
         work, but with embedded function calls instead of static values
    -->
    <xacro:property name="angle_0" value="0"/>
    <xacro:property name="angle_15" value="${PI/12}"/>        <!-- 0.2618 -->
    <xacro:property name="angle_30" value="${PI/6}"/>         <!-- 0.5236 -->
    <xacro:property name="angle_45" value="${PI/4}"/>         <!-- 0.7854 -->
    <xacro:property name="angle_60" value="${PI/3}"/>         <!-- 1.0472 -->
    <xacro:property name="angle_90" value="${PI/2}"/>         <!-- 1.0472 -->
    <xacro:property name="angle_120" value="${2*PI/3}"/>      <!-- 2.0944 -->
    <xacro:property name="angle_135" value="${3*PI/4}"/>      <!-- 2.3562 -->
    <xacro:property name="angle_150" value="${5*PI/6}"/>      <!-- 2.6180 -->
    <xacro:property name="angle_165" value="${11*PI/12}"/>    <!-- 2.8800 -->
    <xacro:property name="angle_180" value="${PI}"/>          <!-- 3.1416 -->
    <xacro:property name="angle_195" value="${13*PI/12}"/>    <!-- 3.4000 -->
    <xacro:property name="angle_210" value="${7*PI/6}"/>      <!-- 3.6652 -->
    <xacro:property name="angle_225" value="${5*PI/4}"/>      <!-- 3.9270 -->
    <xacro:property name="angle_240" value="${4*PI/3}"/>      <!-- 4.1888 -->
    <xacro:property name="angle_300" value="${5*PI/3}"/>      <!-- 5.2360 -->
    <xacro:property name="angle_315" value="${7*PI/4}"/>      <!-- 5.4978 -->
    <xacro:property name="angle_330" value="${11*PI/6}"/>     <!-- 5.7596 -->
    <xacro:property name="angle_345" value="${23*PI/24}"/>    <!-- 5.2360 -->

    <xacro:property name="cos_angle_0" value="1.0000"/>
    <xacro:property name="cos_angle_15" value="0.9659"/>
    <xacro:property name="cos_angle_30" value="0.8660"/>
    <xacro:property name="cos_angle_45" value="0.7071"/>
    <xacro:property name="cos_angle_60" value="0.5000"/>
    <xacro:property name="cos_angle_120" value="-0.5000"/>
    <xacro:property name="cos_angle_135" value="-0.7071"/>
    <xacro:property name="cos_angle_150" value="-0.8660"/>
    <xacro:property name="cos_angle_165" value="-0.9659"/>
    <xacro:property name="cos_angle_180" value="-1.0000"/>
    <xacro:property name="cos_angle_195" value="-0.9659"/>
    <xacro:property name="cos_angle_210" value="-0.8660"/>
    <xacro:property name="cos_angle_225" value="-0.7071"/>
    <xacro:property name="cos_angle_240" value="-0.5000"/>
    <xacro:property name="cos_angle_300" value="0.5000"/>
    <xacro:property name="cos_angle_315" value="0.7071"/>
    <xacro:property name="cos_angle_330" value="0.8660"/>
    <xacro:property name="cos_angle_345" value="0.9659"/>

    <xacro:property name="sin_angle_0" value="0.0000"/>
    <xacro:property name="sin_angle_15" value="0.2588"/>
    <xacro:property name="sin_angle_30" value="0.5000"/>
    <xacro:property name="sin_angle_45" value="0.7071"/>
    <xacro:property name="sin_angle_60" value="0.8660"/>
    <xacro:property name="sin_angle_120" value="0.8660"/>
    <xacro:property name="sin_angle_135" value="0.7071"/>
    <xacro:property name="sin_angle_150" value="0.5000"/>
    <xacro:property name="sin_angle_165" value="0.2588"/>
    <xacro:property name="sin_angle_180" value="0.0000"/>
    <xacro:property name="sin_angle_195" value="-0.2588"/>
    <xacro:property name="sin_angle_210" value="-0.5000"/>
    <xacro:property name="sin_angle_225" value="-0.7071"/>
    <xacro:property name="sin_angle_240" value="-0.8660"/>
    <xacro:property name="sin_angle_300" value="-0.8660"/>
    <xacro:property name="sin_angle_315" value="-0.7071"/>
    <xacro:property name="sin_angle_330" value="-0.5000"/>
    <xacro:property name="sin_angle_345" value="-0.2588"/>

    <!-- Component parameters -->

    <xacro:property name="ultrasonic_length" value="0.0174"/>
    <xacro:property name="ultrasonic_width" value="0.05"/>
    <xacro:property name="ultrasonic_height" value="0.055"/>

    <xacro:property name="infrared_length" value="0.01"/>
    <xacro:property name="infrared_width" value="0.035"/>
    <xacro:property name="infrared_height" value="0.01"/>

    <xacro:property name="platter_radius" value="0.2286" />
    <xacro:property name="platter_height" value="0.009525" />

    <xacro:property name="battery_box_size_x" value="0.1778" />
    <xacro:property name="battery_box_size_y" value="0.36195" />
    <xacro:property name="battery_box_size_z" value="0.0762" />

    <xacro:property name="standoff_height" value="0.127"/>

    <!-- Note: wheel length is the wheel width -->
    <xacro:property name="wheel_length" value="0.0254" />
    <xacro:property name="wheel_radius" value="0.0762" />

    <!-- Note: For Arlobot, the wheel is offset (positive Z axis) relative to the battery box -->
    <xacro:property name="wheel_offset_x" value="0.00" />
    <xacro:property name="wheel_offset_y" value="${battery_box_size_y/2 + wheel_length}" />
    <xacro:property name="wheel_offset_z" value="0.0178" />

    <!-- Base offset values -->
    <xacro:property name="base_size_x" value="${battery_box_size_x}" />
    <xacro:property name="base_size_y" value="${battery_box_size_y}" />
    <xacro:property name="base_size_z" value="${battery_box_size_z}" />
    <xacro:property name="base_offset_z" value="${wheel_radius - wheel_offset_z}"/>

    <!-- Base level offset values -->
    <xacro:property name="baselevel_offset_x" value="0" />
    <xacro:property name="baselevel_offset_y" value="0" />
    <xacro:property name="baselevel_offset_z" value="${base_size_z/2 + platter_height/2}" />
    <!-- Note: baselevel_top_offset_z is relative to the parent -->
    <xacro:property name="baselevel_top_offset_z" value="${platter_height/2}"/>

    <!-- Middle level offset values -->
    <xacro:property name="midlevel_offset_x" value="0"/>
    <xacro:property name="midlevel_offset_y" value="0"/>
    <xacro:property name="midlevel_offset_z" value="${standoff_height + platter_height/2}"/>
    <!-- Note: midlevel_top_offset_z is relative to the parent -->
    <xacro:property name="midlevel_top_offset_z" value="${platter_height/2}"/>

    <!-- Top level offset values -->
    <xacro:property name="toplevel_offset_x" value="0"/>
    <xacro:property name="toplevel_offset_y" value="0"/>
    <xacro:property name="toplevel_offset_z" value="${standoff_height + platter_height/2}"/>
    <!-- Note: toplevel_top_offset_z is relative to the parent -->
    <xacro:property name="toplevel_top_offset_z" value="${platter_height/2}"/>


</robot>