<?xml version="1.0"?>

<robot name="xv11_laser" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- A box-and-cylinder XV11 laser scanner -->
  <property name="xv11_laser_bottom_size_x" value="0.1238"/>
  <property name="xv11_laser_bottom_size_y" value="0.1048"/>
  <property name="xv11_laser_bottom_size_z" value="0.0841"/>
  <property name="xv11_laser_disk_radius" value="0.0381"/>
  <property name="xv11_laser_disk_height" value="0.0144"/>

  <property name="xv11_laser_size_x" value="${xv11_laser_bottom_size_x}"/>
  <property name="xv11_laser_size_y" value="${xv11_laser_bottom_size_y}"/>
  <property name="xv11_laser_size_z" value="${xv11_laser_bottom_size_z + xv11_laser_disk_height}"/>


  <!-- Define the laser macro -->
  <macro name="xv11_laser" params="parent color">
    <joint name="${parent}_laser_bottom_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="${parent}_link"/>
      <child link="base_laser_bottom"/>
    </joint>

    <link name="base_laser_bottom">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${xv11_laser_bottom_size_x} ${xv11_laser_bottom_size_y} ${xv11_laser_bottom_size_x}" />
        </geometry>
       <material name="${color}" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${xv11_laser_bottom_size_x} ${xv11_laser_bottom_size_y} ${xv11_laser_bottom_size_x}" />
        </geometry>
      </collision>
      <inertial>
        <mass value="0.1" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
      </inertial>
    </link>

    <link name="base_laser_middle">
	  <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
		<geometry>
          <cylinder length="0.0115" radius=".02"/>
        </geometry>
        <material name="dark_grey">
           <color rgba="0.2 0.2 0.2 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
		 <geometry>
          <cylinder length="0.0115" radius=".02"/>
         </geometry>
      </collision>
	  <inertial>
        <mass value="0.1" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
       </inertial>
   </link>

   <joint name="base_laser_middle_joint" type="fixed">
     <parent link="base_laser_bottom"/>
     <child link="base_laser_middle" />
     <origin xyz="0 0 0.02625" rpy="0 0 0" />
   </joint>

   <link name="base_laser">
	 <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
		<geometry>
          <cylinder length="0.0175" radius=".0185"/>
        </geometry>
        <material name="red">
           <color rgba="0.8 0.1 0.1 1.0"/>
        </material>
     </visual>
     <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
		 <geometry>
          <cylinder length="${xv11_laser_disk_height}" radius="${xv11_laser_disk_radius}"/>
         </geometry>
       </collision>
	 <inertial>
       <mass value="0.1" />
         <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
      </inertial>
   </link>

   <joint name="base_laser_joint" type="fixed">
     <parent link="base_laser_middle"/>
     <child link="base_laser" />
     <origin xyz="0 0 0.0145" rpy="0 0 0" />
   </joint>

  </macro>

 </robot>